name: Validation Docker build

on:
  push:
    branches: [master,dev]
  pull_request:
    branches: [master,dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: build docker-img & script shell to validar the docker build
        run: |
          docker build -t myapp .
          if [ $? -eq 0 ]; then
          echo "El build es correcto"
          else
          echo "El build es incorrecto"
          exit 1
          fi
      - name: Send mesage to Discord
        if: ${{ failure() }} 
        run: |
          curl -H "Content-Type: application/json" -d '{"username": "test", "content": "hello"}' ${{ secrets.WEBHOOK_TOKEN }}

      - name: Docker Lint
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: 'Dockerfile'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}